---
title: "`meth3D`"
subtitle: "Simulation of mediation scheme"
author: "Florent Chuffart, Daniel Jost"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---



```{r, echo=FALSE, eval=TRUE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=12, fig.height=6, eval=TRUE, echo=TRUE, results="verbatim", dpi=75)
```


# Simulation

<>## Params {-}

```{r}
source("params.R")
print(suffix)
simusres_filename = paste0("sim_res_", suffix, ".txt")
simu0res_filename = paste0("sim_res_seed0", "_", paste0(strsplit(suffix, "_")[[1]][-1], collapse="_")
, ".txt")
infos = list()
```

## Launch simulator  {-}

```{r simu}
simuexectime_filename = paste0("exectime_", suffix, ".rds")
if (!file.exists(simusres_filename)) {
  params_filename = paste0("params_", suffix, ".txt")
  cat(paste0("ncell=", ncell, "     \n"), file=params_filename)
  cat(paste0("i = ", i, "           \n"), file=params_filename, append=TRUE)
  cat(paste0("sij = ", sij, "       \n"), file=params_filename, append=TRUE)
  cat(paste0("gamma1 = ", gamma1, " \n"), file=params_filename, append=TRUE)
  cat(paste0("gamma2 = ", gamma2, " \n"), file=params_filename, append=TRUE)
  cat(paste0("d = ", d, "           \n"), file=params_filename, append=TRUE)
  cat(paste0("lamb = ", lamb, "     \n"), file=params_filename, append=TRUE)
  cat(paste0("f = ", f, "           \n"), file=params_filename, append=TRUE)
  cat(paste0("seed = ", seed, "           \n"), file=params_filename, append=TRUE)
  cmd = "python"
  args = paste("simulator.py", params_filename)
  print(paste(cmd, args))
  start_time = Sys.time()
  system2(cmd, args)
  stop_time = Sys.time()
  exectime = round(difftime(stop_time, start_time, units="mins"),1)
  saveRDS(exectime, simuexectime_filename)
}
infos$simuexectime = readRDS(simuexectime_filename)

if (!file.exists(simusres_filename)) {stop(paste0("no file ", simusres_filename, " produced."))}
```


# Session Information

```{r}
saveRDS(infos, paste0("infos_", suffix, ".rds"))
sessionInfo()
```